# Generated by Django 3.2.22 on 2023-11-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0338_auto_20231010_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='variant_id',
            field=models.UUIDField(help_text='The identifier for a product variant.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='variant_id',
            field=models.UUIDField(help_text='The identifier for a product variant.', null=True),
        ),
    ]
